def ecdh():
    hide_all_frames()
    ecdh_frame.pack(fill="both", expand=1)
    print("Operaciones de Puntos:")
    curve = EllipticCurve(-7, 10)
    p = Point(1, 2)
    #q = Point(3, 4)
    r = curve.point_mult(p, 4)
    print("-------")
    print(r.get_x())
    print("-------")
    print(r.get_y())
    print("////////////////////////")
    print("ECDH:")
    bob = User()
    alice = User()
    g = Point(1, 2)
    print("El punto generador G es:")
    print(g.print())
    print("-------")

    print("Clave PRIVADA de Alice:")
    alice.setPrivKey(6)
    print(alice.getPrivKey())
    print("Clave PÚBLICA de Alice:")
    alice.setPubKey(curve.point_mult(g, alice.getPrivKey()))
    print(alice.getPubKey().print())
    print("-------")

    print("Clave PRIVADA de Bob:")
    bob.setPrivKey(8)
    print(bob.getPrivKey())
    print("Clave PÚBLICA de Bob:")
    bob.setPubKey(curve.point_mult(g, bob.getPrivKey()))
    print(bob.getPubKey().print())
    print("-------")

    print("Clave COMPARTIDA calculada por ALICE:")
    print(curve.point_mult(bob.getPubKey(), alice.getPrivKey()).print())
    print("-------")

    print("Clave COMPARTIDA calculada por BOB:")
    print(curve.point_mult(alice.getPubKey(), bob.getPrivKey()).print())
    print("-------")